Traceback (most recent call last):
  File "/home/aquathi/.local/share/pipx/venvs/jupyter-book/lib/python3.12/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/home/aquathi/.local/share/pipx/venvs/jupyter-book/lib/python3.12/site-packages/nbclient/client.py", line 1314, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aquathi/.local/share/pipx/venvs/jupyter-book/lib/python3.12/site-packages/jupyter_core/utils/__init__.py", line 165, in wrapped
    return loop.run_until_complete(inner)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/asyncio/base_events.py", line 687, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/home/aquathi/.local/share/pipx/venvs/jupyter-book/lib/python3.12/site-packages/nbclient/client.py", line 709, in async_execute
    await self.async_execute_cell(
  File "/home/aquathi/.local/share/pipx/venvs/jupyter-book/lib/python3.12/site-packages/nbclient/client.py", line 1062, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/home/aquathi/.local/share/pipx/venvs/jupyter-book/lib/python3.12/site-packages/nbclient/client.py", line 918, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
def plot_precision(kmax):
    import matplotlib.pyplot as plt
    R = range(1, kmax)
    plt.plot(R, [precision(k) for k in R])
    plt.show()

plot_precision(5)
------------------


[0;31m---------------------------------------------------------------------------[0m
[0;31mModuleNotFoundError[0m                       Traceback (most recent call last)
Cell [0;32mIn[21], line 7[0m
[1;32m      4[0m     plt[38;5;241m.[39mplot(R, [precision(k) [38;5;28;01mfor[39;00m k [38;5;129;01min[39;00m R])
[1;32m      5[0m     plt[38;5;241m.[39mshow()
[0;32m----> 7[0m [43mplot_precision[49m[43m([49m[38;5;241;43m5[39;49m[43m)[49m

Cell [0;32mIn[21], line 2[0m, in [0;36mplot_precision[0;34m(kmax)[0m
[1;32m      1[0m [38;5;28;01mdef[39;00m [38;5;21mplot_precision[39m(kmax):
[0;32m----> 2[0m     [38;5;28;01mimport[39;00m [38;5;21;01mmatplotlib[39;00m[38;5;21;01m.[39;00m[38;5;21;01mpyplot[39;00m [38;5;28;01mas[39;00m [38;5;21;01mplt[39;00m
[1;32m      3[0m     R [38;5;241m=[39m [38;5;28mrange[39m([38;5;241m1[39m, kmax)
[1;32m      4[0m     plt[38;5;241m.[39mplot(R, [precision(k) [38;5;28;01mfor[39;00m k [38;5;129;01min[39;00m R])

[0;31mModuleNotFoundError[0m: No module named 'matplotlib'

